version: '3.8'

services:
  core:
    build:
      context: core
    command: ["http-server", "/usr/storybook", "--silent", "--proxy", "http://localhost:8080?"]
    environment:
      - PORT=6006
    ports:
      - 6006:6006
