apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui-core-ingress
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
      - {{.Values.namespace}}-ui.scalara.de
      secretName: {{.Values.namespace}}-ui-core-tls

  rules:
    - host: {{.Values.namespace}}-ui.scalara.de
      http:
        paths:
          - path: /
            backend:
              serviceName: ui-core-service
              servicePort: 80